[package]
name = "blockchain-serde-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
arrow = "54"
arrow_convert = "0.8.1"
cherry-core = "0.4"
faster-hex = "0.10"
